[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[deploy]
tx ansible_host=127.0.0.1 ansible_connection=local

[us]
us ansible_host=43.135.167.116 ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[master]
m1 ansible_host=192.168.1.51 ansible_host=m1
m2 ansible_host=192.168.1.52 ansible_host=m2
m3 ansible_host=192.168.1.53 ansible_host=m3

[worker]
w1 ansible_host=192.168.1.54 ansible_host=w1
w2 ansible_host=192.168.1.55 ansible_host=w2

[harbor]
hb ansible_host=192.168.1.61 ansible_host=hb

[tt]
tt ansible_host=192.168.1.71 ansible_host=tt

[k8s:children]
master
worker

[vm:children]
master
worker
harbor
tt